ck\UsersBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        favoriteRecipes:
            targetEntity: ck\RecipesBundle\Entity\Recipe
            inversedBy: users
            joinTable:
                name: bind_users_favorite_recipes
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    recipe_id:
                        referencedColumnName: id