imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'ckApplicationBundle:Form:default_fields.html.twig'

sensio_framework_extra:
    view:
        annotations: false

# FOS User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ck\UsersBundle\Entity\User

# FOS REST
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

# FOS Elastica
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        td:
            client: default
            types:
                Recipe:
                    mappings:
                        name: ~
                        ingredients: 
                            type: "nested"
                            properties:
                                name: ~
                        tags:
                            type: "nested"
                            properties:
                                name: ~
                                id : 
                                    type : integer
                        categories:
                            type: "nested"
                            properties:
                                name: ~
                                id : 
                                    type : integer

                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  ck\RecipesBundle\Entity\Recipe
                        repository: ck\RecipesBundle\Entity\RecipesRepository
                        provider: ~
                        listener: ~
                        finder: ~
                Ingredient:
                    mappings:
                        name: ~
                    persistence:
                        driver: orm
                        model:  ck\RecipesBundle\Entity\Ingredient
                        provider: ~
                        listener: ~
                        finder: ~
                Tags:
                    mappings:
                        name: ~
                    persistence:
                        driver: orm
                        model:  ck\RecipesBundle\Entity\RecipesTag
                        provider: ~
                        listener: ~
                        finder: ~
                Category:
                    mappings:
                        name: ~
                    persistence:
                        driver: orm
                        model:  ck\RecipesBundle\Entity\RecipesCategory
                        provider: ~
                        listener: ~
                        finder: ~

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web

    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web

    driver: gd

    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [75, 75], mode: outbound }
        cocktail_view:
            quality: 75
            filters:
                thumbnail: { size: [600, 600], mode: outbound }

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:

    # Menu
    application.menu_builder:
        class: ck\ApplicationBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    application.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: application.menu_builder
        factory_method: createMainMenu
        arguments: [@request, @security.context, @service_container]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
        - { name: twig.extension }
